spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-product
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: liquibase/changelog-master.yml
server:
  port: 8080
